// <auto-generated />
namespace foodisgood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProductsStrippedDown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductsStrippedDown));
        
        string IMigrationMetadata.Id
        {
            get { return "202105220607044_ProductsStrippedDown"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
